version: '3.9'

services:
  postgres_primary:
    image: postgres:16.4-alpine3.20
    container_name: postgres_primary
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./init_thai.sh:/docker-entrypoint-initdb.d/init_thai.sh
      - ./data/primary:/var/lib/postgresql/data
      - ./primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 45s
      retries: 10
    restart: always

  postgres_replica:
    image: postgres:16.4-alpine3.20
    container_name: postgres_replica
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/replica:/var/lib/postgresql/data
      - ./replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./replica/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    depends_on:
      - postgres_primary
    restart: always