version: '3.9'

services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    ports:
      - "6432:6432"
    environment:
      - POSTGRES_PORT=6432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 45s
      retries: 10
    restart: always
